# Info
title: Madan Mohan
tagline: Research Fellow | Cancer Science Institute, NUS
url: https://madanmohanuk.com/
baseurl: ''

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist

# Permalinks
permalink: /:categories/:title

